"""Typed, domain-neutral Codex app-server client support."""

from .compatibility import (
    PINNED_PROTOCOL,
    BinaryIdentity,
    CompatibilityResult,
    ProtocolTarget,
    inspect_compatibility,
    resolve_codex_binary,
)
from .errors import (
    AmbiguousCodexBinaryError,
    AppServerClientError,
    CodexBinaryNotFoundError,
    CodexVersionError,
    CorrelationError,
    InitializationError,
    JsonRpcFramingError,
    JsonRpcValidationError,
    MessageTooLargeError,
    RemoteRpcError,
    RequestLimitError,
    SchemaMalformedError,
    SchemaMissingError,
    SchemaRootMismatchError,
    SessionStateError,
    TransportCleanupError,
    TransportClosedError,
    TransportOwnershipError,
    TransportStartError,
    UnsupportedFeatureError,
)
from .models import (
    ClientIdentity,
    ReviewStartParams,
    ReviewStartResponse,
    ThreadListParams,
    ThreadListResponse,
    ThreadReadParams,
    ThreadReadResponse,
    ThreadResumeParams,
    ThreadResumeResponse,
    ThreadStartParams,
    ThreadStartResponse,
    TurnInterruptParams,
    TurnInterruptResponse,
    TurnStartParams,
    TurnStartResponse,
    TurnSteerParams,
    TurnSteerResponse,
)
from .rpc import ByteChannel
from .session import AppServerClient, AppServerSession, ClientLimits
from .surface import (
    CallbackCapability,
    FeatureSet,
    NotificationCapability,
    RequestCapability,
    TransportCapability,
)
from .transport import (
    ClientTransport,
    InjectedTransport,
    StdioTransport,
    TransportOwnership,
    UnixSocketTransport,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "PINNED_PROTOCOL",
    "AmbiguousCodexBinaryError",
    "AppServerClientError",
    "BinaryIdentity",
    "CallbackCapability",
    "ByteChannel",
    "CodexBinaryNotFoundError",
    "CodexVersionError",
    "CorrelationError",
    "CompatibilityResult",
    "ClientIdentity",
    "ClientLimits",
    "ClientTransport",
    "FeatureSet",
    "NotificationCapability",
    "ProtocolTarget",
    "RequestCapability",
    "JsonRpcFramingError",
    "JsonRpcValidationError",
    "InjectedTransport",
    "InitializationError",
    "MessageTooLargeError",
    "RemoteRpcError",
    "RequestLimitError",
    "ReviewStartParams",
    "ReviewStartResponse",
    "SchemaMalformedError",
    "SchemaMissingError",
    "SchemaRootMismatchError",
    "StdioTransport",
    "SessionStateError",
    "AppServerClient",
    "AppServerSession",
    "ThreadListParams",
    "ThreadListResponse",
    "ThreadReadParams",
    "ThreadReadResponse",
    "ThreadResumeParams",
    "ThreadResumeResponse",
    "ThreadStartParams",
    "ThreadStartResponse",
    "TransportCleanupError",
    "TransportClosedError",
    "TransportCapability",
    "TransportOwnership",
    "TransportOwnershipError",
    "TransportStartError",
    "TurnInterruptParams",
    "TurnInterruptResponse",
    "TurnStartParams",
    "TurnStartResponse",
    "TurnSteerParams",
    "TurnSteerResponse",
    "UnixSocketTransport",
    "UnsupportedFeatureError",
    "inspect_compatibility",
    "resolve_codex_binary",
]
