"""Typed, domain-neutral Codex app-server client support."""

from .compatibility import (
    PINNED_PROTOCOL,
    BinaryIdentity,
    CompatibilityResult,
    ProtocolTarget,
    inspect_compatibility,
    resolve_codex_binary,
)
from .errors import (
    AmbiguousCodexBinaryError,
    AppServerClientError,
    CodexBinaryNotFoundError,
    CodexVersionError,
    CorrelationError,
    JsonRpcFramingError,
    JsonRpcValidationError,
    MessageTooLargeError,
    RemoteRpcError,
    RequestLimitError,
    SchemaMalformedError,
    SchemaMissingError,
    SchemaRootMismatchError,
    TransportCleanupError,
    TransportClosedError,
    TransportOwnershipError,
    TransportStartError,
    UnsupportedFeatureError,
)
from .rpc import ByteChannel
from .surface import (
    CallbackCapability,
    FeatureSet,
    NotificationCapability,
    RequestCapability,
    TransportCapability,
)
from .transport import (
    ClientTransport,
    InjectedTransport,
    StdioTransport,
    TransportOwnership,
    UnixSocketTransport,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "PINNED_PROTOCOL",
    "AmbiguousCodexBinaryError",
    "AppServerClientError",
    "BinaryIdentity",
    "CallbackCapability",
    "ByteChannel",
    "CodexBinaryNotFoundError",
    "CodexVersionError",
    "CorrelationError",
    "CompatibilityResult",
    "ClientTransport",
    "FeatureSet",
    "NotificationCapability",
    "ProtocolTarget",
    "RequestCapability",
    "JsonRpcFramingError",
    "JsonRpcValidationError",
    "InjectedTransport",
    "MessageTooLargeError",
    "RemoteRpcError",
    "RequestLimitError",
    "SchemaMalformedError",
    "SchemaMissingError",
    "SchemaRootMismatchError",
    "StdioTransport",
    "TransportCleanupError",
    "TransportClosedError",
    "TransportCapability",
    "TransportOwnership",
    "TransportOwnershipError",
    "TransportStartError",
    "UnixSocketTransport",
    "UnsupportedFeatureError",
    "inspect_compatibility",
    "resolve_codex_binary",
]
